FROM eclipse-temurin:21-jdk-jammy
LABEL org.opencontainers.image.source=https://github.com/opendonationasssistant/oda-payment-processing
WORKDIR /app
COPY target/oda-payment-processing-0.1.jar /app

CMD ["java","--add-opens","java.base/java.time=ALL-UNNAMED","-jar","oda-payment-processing-0.1.jar"]
