micronaut:
  serde:
    serialization:
      inclusion: ALWAYS
  application:
    name: oda-payment-processing
  security:
    authentication: bearer
    token:
      bearer:
        enabled: true
      cookie:
        enabled: true
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ${JWKS_URI}
endpoints:
  flyway:
    enabled: true
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      schemas: 'processing'
      default-schema: 'processing'
jpa:
  default:
    entity-scan:
        packages: 'io.github.opendonationassistant'
