name: Release

on:
  push:
    branches: ["main"]

permissions: write-all

jobs:
  build-and-deploy:
    uses: "OpenDonationAssistant/oda-libraries/.github/workflows/release_service.yml@master"
    secrets: inherit
    with:
      service: payment-processing
      version: "${{ github.RUN_NUMBER }}"
